
# This file is automatically generated, you probably don't want to edit this

fdistOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fdistOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            p = 0.95,
            df1 = 2,
            df2 = 10, ...) {

            super$initialize(
                package="Critical",
                name="fdist",
                requiresData=FALSE,
                ...)

            private$..p <- jmvcore::OptionNumber$new(
                "p",
                p,
                default=0.95)
            private$..df1 <- jmvcore::OptionNumber$new(
                "df1",
                df1,
                default=2)
            private$..df2 <- jmvcore::OptionNumber$new(
                "df2",
                df2,
                default=10)

            self$.addOption(private$..p)
            self$.addOption(private$..df1)
            self$.addOption(private$..df2)
        }),
    active = list(
        p = function() private$..p$value,
        df1 = function() private$..df1$value,
        df2 = function() private$..df2$value),
    private = list(
        ..p = NA,
        ..df1 = NA,
        ..df2 = NA)
)

fdistResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fdistResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="F")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Critical Value"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Density",
                width=400,
                height=300,
                renderFun=".plot"))}))

fdistBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fdistBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Critical",
                name = "fdist",
                version = c(1,0,0),
                options = options,
                results = fdistResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' F
#'
#' 
#' @param p .
#' @param df1 .
#' @param df2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
fdist <- function(
    p = 0.95,
    df1 = 2,
    df2 = 10) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("fdist requires jmvcore to be installed (restart may be required)")


    options <- fdistOptions$new(
        p = p,
        df1 = df1,
        df2 = df2)

    analysis <- fdistClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

