
# This file is automatically generated, you probably don't want to edit this

normalOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "normalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            group = NULL,
            p = 0.95,
            mean = 10,
            sd = 5, ...) {

            super$initialize(
                package="Critical",
                name="normal",
                requiresData=FALSE,
                ...)

            private$..group <- jmvcore::OptionList$new(
                "group",
                group,
                options=list(
                    "Two-sided",
                    "One-sided"))
            private$..p <- jmvcore::OptionNumber$new(
                "p",
                p,
                default=0.95)
            private$..mean <- jmvcore::OptionNumber$new(
                "mean",
                mean,
                default=10)
            private$..sd <- jmvcore::OptionNumber$new(
                "sd",
                sd,
                default=5)

            self$.addOption(private$..group)
            self$.addOption(private$..p)
            self$.addOption(private$..mean)
            self$.addOption(private$..sd)
        }),
    active = list(
        group = function() private$..group$value,
        p = function() private$..p$value,
        mean = function() private$..mean$value,
        sd = function() private$..sd$value),
    private = list(
        ..group = NA,
        ..p = NA,
        ..mean = NA,
        ..sd = NA)
)

normalResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "normalResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Normal")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Critical Value"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Density",
                width=400,
                height=300,
                renderFun=".plot"))}))

normalBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "normalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Critical",
                name = "normal",
                version = c(1,0,0),
                options = options,
                results = normalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Normal
#'
#' 
#' @param group .
#' @param p .
#' @param mean .
#' @param sd .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
normal <- function(
    group,
    p = 0.95,
    mean = 10,
    sd = 5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("normal requires jmvcore to be installed (restart may be required)")


    options <- normalOptions$new(
        group = group,
        p = p,
        mean = mean,
        sd = sd)

    analysis <- normalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

