
# This file is automatically generated, you probably don't want to edit this

quantileOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "quantileOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            group = NULL,
            p = 0.95, ...) {

            super$initialize(
                package="Critical",
                name="quantile",
                requiresData=FALSE,
                ...)

            private$..group <- jmvcore::OptionList$new(
                "group",
                group,
                options=list(
                    "Two-sided",
                    "One-sided"))
            private$..p <- jmvcore::OptionNumber$new(
                "p",
                p,
                default=0.95)

            self$.addOption(private$..group)
            self$.addOption(private$..p)
        }),
    active = list(
        group = function() private$..group$value,
        p = function() private$..p$value),
    private = list(
        ..group = NA,
        ..p = NA)
)

quantileResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "quantileResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Critical Value")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Critical Value"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Density",
                width=400,
                height=300,
                renderFun=".plot"))}))

quantileBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "quantileBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Critical",
                name = "quantile",
                version = c(1,0,0),
                options = options,
                results = quantileResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Standard Normal
#'
#' 
#' @param group .
#' @param p .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
quantile <- function(
    group,
    p = 0.95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("quantile requires jmvcore to be installed (restart may be required)")


    options <- quantileOptions$new(
        group = group,
        p = p)

    analysis <- quantileClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

