
# This file is automatically generated, you probably don't want to edit this

tdistOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tdistOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            p = 0.95,
            df = 10,
            group = NULL, ...) {

            super$initialize(
                package="Critical",
                name="tdist",
                requiresData=FALSE,
                ...)

            private$..p <- jmvcore::OptionNumber$new(
                "p",
                p,
                default=0.95)
            private$..df <- jmvcore::OptionNumber$new(
                "df",
                df,
                default=10)
            private$..group <- jmvcore::OptionList$new(
                "group",
                group,
                options=list(
                    "Two-sided",
                    "One-sided"))

            self$.addOption(private$..p)
            self$.addOption(private$..df)
            self$.addOption(private$..group)
        }),
    active = list(
        p = function() private$..p$value,
        df = function() private$..df$value,
        group = function() private$..group$value),
    private = list(
        ..p = NA,
        ..df = NA,
        ..group = NA)
)

tdistResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tdistResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Student's t")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Critical Value"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Density",
                width=400,
                height=300,
                renderFun=".plot"))}))

tdistBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tdistBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Critical",
                name = "tdist",
                version = c(1,0,0),
                options = options,
                results = tdistResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Student's t distribution
#'
#' 
#' @param p .
#' @param df .
#' @param group .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
tdist <- function(
    p = 0.95,
    df = 10,
    group) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tdist requires jmvcore to be installed (restart may be required)")


    options <- tdistOptions$new(
        p = p,
        df = df,
        group = group)

    analysis <- tdistClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

